application:
    name:        wastrap
    version:     v1.0.2
    author:      institute-atri
    description: Wastrap, is a tool for the recognition of vulnerabilities and blackbox information for wordpress.